name: .NET Core

on:
  push:
    branches: [ v7.0.0.Core ]
  pull_request:
    branches: [ v7.0.0.Core ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/blaise.braye/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}     
    - name: Build with dotnet
      run: dotnet pack --configuration Release -o out
    
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true
